### ISSUE TITLE
Cannot read property 'is' of null

### ISSUE THREAD

**Issue by nika-begiashvili** [PolymerLabs/shady-css-parser#13]
I'm getting error from polymer build

```
error:   Uncaught exception: TypeError: Cannot read property 'is' of null
error:   TypeError: Cannot read property 'is' of null
    at Parser.parseDeclarationOrRuleset (shady-css-parser\dist\shady-css\parser.js:191:33)
    at Parser.parseRule (shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRules (shady-css-parser\dist\shady-css\parser.js:62:25)
    at Parser.parseStylesheet (shady-css-parser\dist\shady-css\parser.js:55:47)
    at Parser.parse (shady-css-parser\dist\shady-css\parser.js:51:19)
    at css (css-slam\index.js:51:39)
    at GulpTransform._transform (css-slam\index.js:69:36)
    at GulpTransform.Transform._read (_stream_transform.js:167:10)
    at GulpTransform.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
```

file on which error occurs is:
https://github.com/vaadin/vaadin-grid/blob/master/demo/common.css

**Comment by karlito-who-else** [comment]
Many thanks @nika-begiashvili  on identifying vaadin-grid as the cause of the issue.  I had thought that my problems were due to upgrading polymer-cli.

There seems to be a fix in the form of https://github.com/vaadin/vaadin-grid/issues/382 that has been merged into master, although there has not yet been a subsequent release in order to fix the bower package.

`bower uninstall vaadin-grid` has fixed my issue in the meantime.

**Comment by cdata** [comment]
Thanks for reporting! I'll take a look.

**Comment by nika-begiashvili** [comment]
I think it would be great if shady-css-parser will report invalid files in console to make it easy to identify invalid components

**Comment by nika-begiashvili** [comment]
here goes another error for
https://github.com/motss/app-datepicker/blob/master/demo/index.html

```
 Uncaught exception: TypeError: Cannot read property 'previous' of null
error:   TypeError: Cannot read property 'previous' of null
    at Parser.parseDeclarationOrRuleset (shady-css-parser\dist\shady-css\parser.js:192:63)

```

**Comment by JPMoresmau** [comment]
I have the same error, and a lot of dependent components, so checking them one by one is not an option. What's the strategy to identify the offending css?

**Comment by jarrodek** [comment]
I believe I've found what causes this issue. Please, see my comment in this issue: https://github.com/PolymerLabs/css-slam/issues/10#issuecomment-308727665
